name: ✅Build Status Check
run-name: ✅Build Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    branches: [main, preview]


jobs:
  build_status_check:
    name: Build Status Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ vars.DENO_VERSION }}

    - name: Run Build
      run: deno check ./**/*.ts
