name: ✅Lint Status Check
run-name: ✅Lint Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    branches: main


jobs:
  lint_status_check:
    name: Lint Status Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        repository: ${{ github.repository }}

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ vars.DENO_VERSION }}

    - name: Run Lint
      run: deno lint
